In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Student Depression Dataset (1).csv')

In [ ]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10454,52980,Female,23.0,Surat,Student,4.0,0.0,7.25,3.0,0.0,Less than 5 hours,Healthy,PhD,Yes,11.0,2.0,No,1.0
10455,52983,Male,23.0,Bangalore,Student,1.0,0.0,5.44,2.0,0.0,More than 8 hours,Healthy,BA,No,10.0,2.0,No,0.0
10456,52986,Male,34.0,Hyderabad,Student,4.0,0.0,7.10,2.0,0.0,5-6 hours,Unhealthy,MD,Yes,12.0,3.0,No,1.0
10457,52988,Female,20.0,Hyderabad,Student,5.0,0.0,9.50,2.0,0.0,More than 8 hours,Healthy,Class 12,No,2.0,4.0,Yes,1.0
10458,52996,Female,21.0,Vadodara,Student,5.0,0.0,5.42,4.0,0.0,Mo,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop('Job Satisfaction',inplace=True,axis=1)

In [ ]:
df.drop('Work Pressure',inplace=True,axis=1)

In [ ]:
df

,id,Gender,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,8.97,2.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,5.90,5.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,7.03,5.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,5.59,2.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,8.13,3.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10454,52980,Female,23.0,Surat,Student,4.0,7.25,3.0,Less than 5 hours,Healthy,PhD,Yes,11.0,2.0,No,1.0
10455,52983,Male,23.0,Bangalore,Student,1.0,5.44,2.0,More than 8 hours,Healthy,BA,No,10.0,2.0,No,0.0
10456,52986,Male,34.0,Hyderabad,Student,4.0,7.10,2.0,5-6 hours,Unhealthy,MD,Yes,12.0,3.0,No,1.0
10457,52988,Female,20.0,Hyderabad,Student,5.0,9.50,2.0,More than 8 hours,Healthy,Class 12,No,2.0,4.0,Yes,1.0
10458,52996,Female,21.0,Vadodara,Student,5.0,5.42,4.0,Mo,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
CGPA                                     0
Study Satisfaction                       0
Sleep Duration                           0
Dietary Habits                           1
Degree                                   1
Have you ever had suicidal thoughts ?    1
Work/Study Hours                         1
Financial Stress                         2
Family History of Mental Illness         1
Depression                               1
dtype: int64

In [ ]:
df['Financial Stress'].fillna(method='ffill',inplace=True)

<ipython-input-42-6d38f6c3781e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Financial Stress'].fillna(method='ffill',inplace=True)
<ipython-input-42-6d38f6c3781e>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Financial Stress'].fillna(method='ffill',inplace=True)

In [ ]:
df.to_csv('Student_Depression.csv',index=False,encoding='utf-8')